spring.application.name=Hospital Management

spring.datasource.url=jdbc:postgresql://localhost:5432/hospital_db
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

# Delay data.sql until after Hibernate creates the tables
spring.jpa.defer-datasource-initialization=true

# Ensure the script runs for all databases (not just embedded ones)
spring.sql.init.mode=always
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
