spring:
  application:
    name: Hospital Management

  datasource:
    url: jdbc:postgresql://localhost:5432/hospital_db
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  # Delay data.sql until after Hibernate creates the tables
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true

  # Ensure the script runs for all databases (not just embedded ones)
  sql:
    init:
      mode: never

  security:
    # user:
    #   name: arnab
    #   password: 1234
    oauth2:
      client:
        registration:
          # Google
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}

server:
  servlet:
    context-path: /api/v1

jwt:
  secretkey: ${JWT_SECRET_KEY}