package com.practice.hp.hospitalmanagement.util.mapper.mapperImpl

import com.practice.hp.hospitalmanagement.dto.PatientDto
import com.practice.hp.hospitalmanagement.entity.Patient
import com.practice.hp.hospitalmanagement.util.mapper.Mapper

class PatientMapper: Mapper<PatientDto, Patient> {
    override fun dtoToEntity(dto: PatientDto): Patient {
        return Patient(
            id = dto.id,
            firstName = dto.firstName,
            lastName = dto.lastName,
            gender = dto.gender,
            email = dto.email,
            // registrationDateTime is auto-generated by @CreationTimestamp, usually skipped here
            // Insurance and Appointments are set by the Service logic
        )
    }

    override fun entityToDto(entity: Patient): PatientDto {
        return PatientDto(
            id = entity.id,
            firstName = entity.firstName,
            lastName = entity.lastName,
            gender = entity.gender,
            email = entity.email,
            registrationDateTime = entity.registrationDateTime,
            // Map the nested Insurance object if it exists
            insurance = entity.insurance?.let { InsuranceMapper().entityToDto(it) },
            // Map the list of Appointment objects to a list of IDs
            appointmentIds = entity.appointments.mapNotNull { it.id }
        )
    }
}